# Generated by Django 2.2.12 on 2020-04-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='verification_key',
            field=models.CharField(blank=True, max_length=30, verbose_name='Verification Key'),
        ),
    ]
