# Generated by Django 2.2.12 on 2020-04-28 14:40

import covexit.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('verification_key', models.CharField(blank=True, max_length=30, verbose_name='Verification Key')),
                ('accepted_privacy_policy', models.BooleanField(validators=[covexit.accounts.models.validate_true], verbose_name='Accepted Privacy Policy')),
            ],
        ),
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='verification_key',
            field=models.CharField(blank=True, max_length=30, verbose_name='Verification Key'),
        ),
    ]
