# Generated by Django 2.2.12 on 2020-04-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200411_0249'),
        ('accounts', '0001_initial'),
    ]

    operations = [
    ]
