# Generated by Django 2.2.12 on 2020-04-17 08:20

import covexit.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20200417_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='accepted_privacy_policy',
            field=models.BooleanField(default=True, validators=[covexit.accounts.models.validate_true], verbose_name='Accepted Privacy Policy'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='accepted_tos',
            field=models.BooleanField(default=True, validators=[covexit.accounts.models.validate_true], verbose_name='Accepted ToS'),
        ),
    ]
