# Generated by Django 2.2.12 on 2020-04-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Order has been read'),
        ),
    ]
