# Generated by Django 2.2.12 on 2020-04-07 21:55

import covexit.account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('zip_and_city', models.CharField(max_length=200, verbose_name='Zip and City')),
                ('phone', models.CharField(default='', max_length=45, verbose_name='Phone')),
                ('accepted_tos', models.BooleanField(validators=[covexit.account.models.validate_true], verbose_name='Accepted ToS')),
                ('accepted_privacy_policy', models.BooleanField(validators=[covexit.account.models.validate_true], verbose_name='Accepted Privacy Policy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
