# Generated by Django 2.2.12 on 2020-04-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
    ]
