# Generated by Django 2.2.12 on 2020-04-25 00:00

import covexit.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200411_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('verification_key', models.CharField(blank=True, max_length=30, verbose_name='Verification Key')),
                ('accepted_privacy_policy', models.BooleanField(verbose_name='Accepted Privacy Policy')),
            ],
        ),
    ]
