# Generated by Django 2.2.12 on 2020-04-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_key',
            field=models.CharField(default='WEFIOUHWEIOJONNIofjweosnkcvo', max_length=30, verbose_name='Verification Key'),
            preserve_default=False,
        ),
    ]
