# Generated by Django 2.2.12 on 2020-04-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_add_waiting_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglistentry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
