# Generated by Django 2.2.12 on 2020-04-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_make_waitinglist_email_unique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaitingListEntry',
            new_name='MailingListEntry',
        ),
    ]
