# Generated by Django 2.2.12 on 2020-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200501_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistentry',
            name='verified',
            field=models.BooleanField(default=False, help_text='<a href="../resend_verification">Send key again</a>', verbose_name='Email Verified'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='verified',
            field=models.BooleanField(default=False, help_text='<a href="../resend_verification">Send key again</a>', verbose_name='Email Verified'),
        ),
    ]
