# Generated by Django 2.2.12 on 2020-05-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_use_email_instead_of_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglistentry',
            name='accepted_privacy_policy',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='accepted_privacy_policy',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='accepted_tos',
        ),
    ]
