# Generated by Django 2.2.11 on 2020-03-27 20:01

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A company with that name already exists.'}, help_text='65 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=65, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='registered company name')),
                ('mail', models.EmailField(max_length=80, verbose_name='e-mail address')),
                ('street', models.CharField(max_length=60, verbose_name='street address')),
                ('city', models.CharField(max_length=45, verbose_name='city')),
                ('phone', models.CharField(max_length=45, verbose_name='phone')),
                ('zip', models.CharField(max_length=10, verbose_name='ZIP Code')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('industry', models.CharField(choices=[('CL', 'Clothes and shoes'), ('EC', 'Electronics'), ('JW', 'Accessoires and Jewellery'), ('BK', 'Books and Office'), ('GD', 'Flowers, Garden and Animals'), ('DS', 'Drugstore and Beauy'), ('TS', 'Toys and Gifts'), ('CF', 'Tea and Coffee'), ('LV', 'Household and Living')], default='CL', max_length=2)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
