# Generated by Django 2.2.11 on 2020-03-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_company_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='website'),
        ),
    ]
