# Generated by Django 2.2.11 on 2020-03-27 22:18

from django.db import migrations


def insert_data(apps, schema_editor):
    Product = apps.get_model("catalogue", "Product")
    ProductCategory = apps.get_model("catalogue", "ProductCategory")
    Company = apps.get_model("companies", "Company")

    groceries, _ = ProductCategory.objects.get_or_create(name="Groceries")
    clothing, _ = ProductCategory.objects.get_or_create(name="Clothing")

    company = Company.objects.first()

    Product.objects.create(
        name="Trail mix",
        image="notfound.jpg",
        price=12.50,
        stock=100,
        description="Lorem ipsum dolor sit amet",
        category=groceries,
        company=company,
    )

    Product.objects.create(
        name="Milk (1L)",
        image="notfound.jpg",
        price=1.5,
        stock=50,
        description="Lorem ipsum dolor sit amet",
        category=groceries,
        company=company,
    )

    Product.objects.create(
        name="T-shirt",
        image="notfound.jpg",
        price=44,
        stock=2,
        description="Lorem ipsum dolor sit amet",
        category=clothing,
        company=company,
    )


class Migration(migrations.Migration):

    dependencies = [("catalogue", "0001_initial"), ("companies", "0002_add_company_data")]

    operations = [migrations.RunPython(insert_data, reverse_code=migrations.RunPython.noop)]
