# Generated by Django 2.2.12 on 2020-04-04 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20181115_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='partner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='industry',
            field=models.CharField(choices=[('CL', 'Clothes and shoes'), ('EC', 'Electronics'), ('JW', 'Accessoires and Jewellery'), ('BK', 'Books and Office'), ('GD', 'Flowers, Garden and Animals'), ('DS', 'Drugstore and Beauy'), ('TS', 'Toys and Gifts'), ('CF', 'Tea and Coffee'), ('LV', 'Household and Living')], default='CL', max_length=2),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(error_messages={'unique': 'A company with that name already exists.'}, help_text='65 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=65, unique=True, verbose_name='registered company name'),
        ),
    ]
