# Generated by Django 2.2.12 on 2020-04-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_add_partner_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='industry',
        ),
    ]
