# Generated by Django 2.2.12 on 2020-04-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_remove_industry_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='description'),
        ),
    ]
