# Generated by Django 2.2.12 on 2020-04-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_add_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.CharField(blank=True, choices=[('business_books.jpg', 'books'), ('business_clothes.jpg', 'clothes'), ('business_coffee.jpg', 'coffee'), ('business_drugstore.jpg', 'drugstore'), ('business_electronics.jpg', 'electronics'), ('business_garden.jpg', 'garden'), ('business_jewellry.jpg', 'jewellry'), ('business_living.jpg', 'living'), ('business_other.jpg', 'other'), ('business_toys.jpg', 'toys')], max_length=50, null=True),
        ),
    ]
