# Generated by Django 2.2.12 on 2020-05-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_add_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneraddress',
            name='vat_no',
            field=models.CharField(default='', max_length=255, verbose_name='VAT number'),
            preserve_default=False,
        ),
    ]
